environment_tags:
  prod: prod
  uat: uat

severity:
  prod:
    cpu:
      warning: 70
      critical: 90
    ebs_queue:
      warning: 5
      critical: 10

  uat:
    cpu:
      warning: 80
      critical: 95
    ebs_queue:
      warning: 10
      critical: 15